/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;

import com.vjshop.generated.db.tables.TDeliveryCorp;
import com.vjshop.generated.db.tables.records.TDeliveryCorpRecord;
import java.sql.Timestamp;
import java.util.List;
import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 物流公司DAO
 */
@Repository
public class TDeliveryCorpDao extends JooqBaseDao<TDeliveryCorpRecord, com.vjshop.entity.TDeliveryCorp, Long> {

    /**
     * Create a new TDeliveryCorpDao without any configuration
     */
    public TDeliveryCorpDao() {
        super(TDeliveryCorp.T_DELIVERY_CORP, com.vjshop.entity.TDeliveryCorp.class);
    }

    /**
     * Create a new TDeliveryCorpDao with an attached configuration
     */
    @Autowired
    public TDeliveryCorpDao(Configuration configuration) {
        super(TDeliveryCorp.T_DELIVERY_CORP, com.vjshop.entity.TDeliveryCorp.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TDeliveryCorp object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchById(Long... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TDeliveryCorp fetchOneById(Long value) {
        return fetchOne(TDeliveryCorp.T_DELIVERY_CORP.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByCreateDate(Timestamp... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByModifyDate(Timestamp... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByVersion(Long... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.VERSION, values);
    }

    /**
     * Fetch records that have <code>orders IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByOrders(Integer... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.ORDERS, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByCode(String... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.CODE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByName(String... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.NAME, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCorp> fetchByUrl(String... values) {
        return fetch(TDeliveryCorp.T_DELIVERY_CORP.URL, values);
    }
}
