/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TDeliveryCenter;
import com.vjshop.generated.db.tables.records.TDeliveryCenterRecord;
import org.apache.commons.collections.CollectionUtils;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Collections;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class TDeliveryCenterDao extends JooqBaseDao<TDeliveryCenterRecord, com.vjshop.entity.TDeliveryCenter, Long> {

    /**
     * Create a new TDeliveryCenterDao without any configuration
     */
    public TDeliveryCenterDao() {
        super(TDeliveryCenter.T_DELIVERY_CENTER, com.vjshop.entity.TDeliveryCenter.class);
    }

    /**
     * Create a new TDeliveryCenterDao with an attached configuration
     */
    @Autowired
    public TDeliveryCenterDao(Configuration configuration) {
        super(TDeliveryCenter.T_DELIVERY_CENTER, com.vjshop.entity.TDeliveryCenter.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TDeliveryCenter object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchById(Long... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TDeliveryCenter fetchOneById(Long value) {
        return fetchOne(TDeliveryCenter.T_DELIVERY_CENTER.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByCreateDate(Timestamp... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByModifyDate(Timestamp... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByVersion(Long... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.VERSION, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByAddress(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>area_name IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByAreaName(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.AREA_NAME, values);
    }

    /**
     * Fetch records that have <code>contact IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByContact(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.CONTACT, values);
    }

    /**
     * Fetch records that have <code>is_default IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByIsDefault(Boolean... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.IS_DEFAULT, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByMemo(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.MEMO, values);
    }

    /**
     * Fetch records that have <code>mobile IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByMobile(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.MOBILE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByName(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.NAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByPhone(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.PHONE, values);
    }

    /**
     * Fetch records that have <code>zip_code IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByZipCode(String... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.ZIP_CODE, values);
    }

    /**
     * Fetch records that have <code>area IN (values)</code>
     */
    public List<com.vjshop.entity.TDeliveryCenter> fetchByArea(Long... values) {
        return fetch(TDeliveryCenter.T_DELIVERY_CENTER.AREA, values);
    }

    public com.vjshop.entity.TDeliveryCenter findDefault() {
        ResultSet res = this.getDslContext().selectFrom(this.getTable()).where(TDeliveryCenter.T_DELIVERY_CENTER.IS_DEFAULT.eq(Boolean.TRUE)).fetchResultSet();
        List<com.vjshop.entity.TDeliveryCenter> tDeliveryCenters = super.resultSet2List(res);
        return CollectionUtils.isEmpty(tDeliveryCenters) ? null : tDeliveryCenters.get(0);
    }

}
