/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TGoodsTag;
import com.vjshop.generated.db.tables.records.TGoodsTagRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Repository
public class TGoodsTagDao extends JooqBaseDao<TGoodsTagRecord, com.vjshop.entity.TGoodsTag, Record2<Long, Long>> {

    public void deleteByGoods(Long id) {
        getDslContext().deleteFrom(TGoodsTag.T_GOODS_TAG).where(TGoodsTag.T_GOODS_TAG.GOODS.eq(id))
                .execute();
    }

    /**
     * Create a new TGoodsTagDao without any configuration
     */
    public TGoodsTagDao() {
        super(TGoodsTag.T_GOODS_TAG, com.vjshop.entity.TGoodsTag.class);
    }

    /**
     * Create a new TGoodsTagDao with an attached configuration
     */
    @Autowired
    public TGoodsTagDao(Configuration configuration) {
        super(TGoodsTag.T_GOODS_TAG, com.vjshop.entity.TGoodsTag.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(com.vjshop.entity.TGoodsTag object) {
        return compositeKeyRecord(object.getGoods(), object.getTags());
    }

    /**
     * Fetch records that have <code>goods IN (values)</code>
     */
    public List<com.vjshop.entity.TGoodsTag> fetchByGoods(Long... values) {
        return fetch(TGoodsTag.T_GOODS_TAG.GOODS, values);
    }

    /**
     * Fetch records that have <code>tags IN (values)</code>
     */
    public List<com.vjshop.entity.TGoodsTag> fetchByTags(Long... values) {
        return fetch(TGoodsTag.T_GOODS_TAG.TAGS, values);
    }
}
