/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TGoodsPromotion;
import com.vjshop.generated.db.tables.records.TGoodsPromotionRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Repository
public class TGoodsPromotionDao extends JooqBaseDao<TGoodsPromotionRecord, com.vjshop.entity.TGoodsPromotion, Record2<Long, Long>> {

    public void deleteByGoods(Long id) {
        getDslContext().deleteFrom(TGoodsPromotion.T_GOODS_PROMOTION).where(TGoodsPromotion.T_GOODS_PROMOTION.GOODS.eq(id))
                .execute();
    }

    /**
     * Create a new TGoodsPromotionDao without any configuration
     */
    public TGoodsPromotionDao() {
        super(TGoodsPromotion.T_GOODS_PROMOTION, com.vjshop.entity.TGoodsPromotion.class);
    }

    /**
     * Create a new TGoodsPromotionDao with an attached configuration
     */
    @Autowired
    public TGoodsPromotionDao(Configuration configuration) {
        super(TGoodsPromotion.T_GOODS_PROMOTION, com.vjshop.entity.TGoodsPromotion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(com.vjshop.entity.TGoodsPromotion object) {
        return compositeKeyRecord(object.getGoods(), object.getPromotions());
    }

    /**
     * Fetch records that have <code>goods IN (values)</code>
     */
    public List<com.vjshop.entity.TGoodsPromotion> fetchByGoods(Long... values) {
        return fetch(TGoodsPromotion.T_GOODS_PROMOTION.GOODS, values);
    }

    /**
     * Fetch records that have <code>promotions IN (values)</code>
     */
    public List<com.vjshop.entity.TGoodsPromotion> fetchByPromotions(Long... values) {
        return fetch(TGoodsPromotion.T_GOODS_PROMOTION.PROMOTIONS, values);
    }
}
