/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TOrderLog;
import com.vjshop.generated.db.tables.records.TOrderLogRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TOrderLogDao extends JooqBaseDao<TOrderLogRecord, com.vjshop.entity.TOrderLog, Long> {

    /**
     * Create a new TOrderLogDao without any configuration
     */
    public TOrderLogDao() {
        super(TOrderLog.T_ORDER_LOG, com.vjshop.entity.TOrderLog.class);
    }

    /**
     * Create a new TOrderLogDao with an attached configuration
     */
    @Autowired
    public TOrderLogDao(Configuration configuration) {
        super(TOrderLog.T_ORDER_LOG, com.vjshop.entity.TOrderLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TOrderLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchById(Long... values) {
        return fetch(TOrderLog.T_ORDER_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TOrderLog fetchOneById(Long value) {
        return fetchOne(TOrderLog.T_ORDER_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByCreateDate(Timestamp... values) {
        return fetch(TOrderLog.T_ORDER_LOG.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByModifyDate(Timestamp... values) {
        return fetch(TOrderLog.T_ORDER_LOG.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByVersion(Long... values) {
        return fetch(TOrderLog.T_ORDER_LOG.VERSION, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByContent(String... values) {
        return fetch(TOrderLog.T_ORDER_LOG.CONTENT, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByOperator(String... values) {
        return fetch(TOrderLog.T_ORDER_LOG.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByType(Integer... values) {
        return fetch(TOrderLog.T_ORDER_LOG.TYPE, values);
    }

    /**
     * Fetch records that have <code>orders IN (values)</code>
     */
    public List<com.vjshop.entity.TOrderLog> fetchByOrders(Long... values) {
        return fetch(TOrderLog.T_ORDER_LOG.ORDERS, values);
    }
}
