/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TParameter;
import com.vjshop.generated.db.tables.records.TParameterRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TParameterDao extends JooqBaseDao<TParameterRecord, com.vjshop.entity.TParameter, Long> {

    /**
     * Create a new TParameterDao without any configuration
     */
    public TParameterDao() {
        super(TParameter.T_PARAMETER, com.vjshop.entity.TParameter.class);
    }

    /**
     * Create a new TParameterDao with an attached configuration
     */
    @Autowired
    public TParameterDao(Configuration configuration) {
        super(TParameter.T_PARAMETER, com.vjshop.entity.TParameter.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TParameter object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchById(Long... values) {
        return fetch(TParameter.T_PARAMETER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TParameter fetchOneById(Long value) {
        return fetchOne(TParameter.T_PARAMETER.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByCreateDate(Timestamp... values) {
        return fetch(TParameter.T_PARAMETER.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByModifyDate(Timestamp... values) {
        return fetch(TParameter.T_PARAMETER.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByVersion(Long... values) {
        return fetch(TParameter.T_PARAMETER.VERSION, values);
    }

    /**
     * Fetch records that have <code>orders IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByOrders(Integer... values) {
        return fetch(TParameter.T_PARAMETER.ORDERS, values);
    }

    /**
     * Fetch records that have <code>parameter_group IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByParameterGroup(String... values) {
        return fetch(TParameter.T_PARAMETER.PARAMETER_GROUP, values);
    }

    /**
     * Fetch records that have <code>names IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByNames(String... values) {
        return fetch(TParameter.T_PARAMETER.NAMES, values);
    }

    /**
     * Fetch records that have <code>product_category IN (values)</code>
     */
    public List<com.vjshop.entity.TParameter> fetchByProductCategory(Long... values) {
        return fetch(TParameter.T_PARAMETER.PRODUCT_CATEGORY, values);
    }
}
