/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TPayment;
import com.vjshop.generated.db.tables.records.TPaymentRecord;
import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@Repository
public class TPaymentDao extends JooqBaseDao<TPaymentRecord, com.vjshop.entity.TPayment, Long> {

    /**
     * Create a new TPaymentDao without any configuration
     */
    public TPaymentDao() {
        super(TPayment.T_PAYMENT, com.vjshop.entity.TPayment.class);
    }

    /**
     * Create a new TPaymentDao with an attached configuration
     */
    @Autowired
    public TPaymentDao(Configuration configuration) {
        super(TPayment.T_PAYMENT, com.vjshop.entity.TPayment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TPayment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchById(Long... values) {
        return fetch(TPayment.T_PAYMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TPayment fetchOneById(Long value) {
        return fetchOne(TPayment.T_PAYMENT.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByCreateDate(Timestamp... values) {
        return fetch(TPayment.T_PAYMENT.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByModifyDate(Timestamp... values) {
        return fetch(TPayment.T_PAYMENT.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByVersion(Long... values) {
        return fetch(TPayment.T_PAYMENT.VERSION, values);
    }

    /**
     * Fetch records that have <code>account IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByAccount(String... values) {
        return fetch(TPayment.T_PAYMENT.ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByAmount(BigDecimal... values) {
        return fetch(TPayment.T_PAYMENT.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>bank IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByBank(String... values) {
        return fetch(TPayment.T_PAYMENT.BANK, values);
    }

    /**
     * Fetch records that have <code>fee IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByFee(BigDecimal... values) {
        return fetch(TPayment.T_PAYMENT.FEE, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByMemo(String... values) {
        return fetch(TPayment.T_PAYMENT.MEMO, values);
    }

    /**
     * Fetch records that have <code>method IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByMethod(Integer... values) {
        return fetch(TPayment.T_PAYMENT.METHOD, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByOperator(String... values) {
        return fetch(TPayment.T_PAYMENT.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>payer IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByPayer(String... values) {
        return fetch(TPayment.T_PAYMENT.PAYER, values);
    }

    /**
     * Fetch records that have <code>payment_method IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByPaymentMethod(String... values) {
        return fetch(TPayment.T_PAYMENT.PAYMENT_METHOD, values);
    }

    /**
     * Fetch records that have <code>sn IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchBySn(String... values) {
        return fetch(TPayment.T_PAYMENT.SN, values);
    }

    /**
     * Fetch a unique record that has <code>sn = value</code>
     */
    public com.vjshop.entity.TPayment fetchOneBySn(String value) {
        return fetchOne(TPayment.T_PAYMENT.SN, value);
    }

    /**
     * Fetch records that have <code>orders IN (values)</code>
     */
    public List<com.vjshop.entity.TPayment> fetchByOrders(Long... values) {
        return fetch(TPayment.T_PAYMENT.ORDERS, values);
    }
}
