/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TPromotionGift;
import com.vjshop.generated.db.tables.records.TPromotionGiftRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Entity - 促销-赠品 关联
 *
 * @author VJSHOP Team
 * @version 4.0
 */
@Repository
public class TPromotionGiftDao extends JooqBaseDao<TPromotionGiftRecord, com.vjshop.entity.TPromotionGift, Record2<Long, Long>> {

    public TPromotionGiftDao() {
        super(TPromotionGift.T_PROMOTION_GIFT, com.vjshop.entity.TPromotionGift.class);
    }

    @Autowired
    public TPromotionGiftDao(Configuration configuration) {
        super(TPromotionGift.T_PROMOTION_GIFT, com.vjshop.entity.TPromotionGift.class, configuration);
    }

    @Override
    protected Record2<Long, Long> getId(com.vjshop.entity.TPromotionGift object) {
        return compositeKeyRecord(object.getGiftPromotions(), object.getGifts());
    }

    /**
     * 获取关联信息
     *
     * @param promotionId
     *            促销ID
     * @return 关联
     */
    public List<com.vjshop.entity.TPromotionGift> find(Long promotionId) {
        return fetch(TPromotionGift.T_PROMOTION_GIFT.GIFT_PROMOTIONS, promotionId);
    }

    /**
     * 删除关联
     *
     * @param promotionId
     *            促销ID
     * @return 影响条数
     */
    public int delete(Long promotionId){
        return getDslContext().deleteFrom(TPromotionGift.T_PROMOTION_GIFT)
                .where(TPromotionGift.T_PROMOTION_GIFT.GIFT_PROMOTIONS.eq(promotionId))
                .execute();
    }

    /**
     * 删除关联
     *
     * @param promotionIds
     *            促销ID
     * @return 影响条数
     */
    public int delete(Long... promotionIds){
        return getDslContext().deleteFrom(TPromotionGift.T_PROMOTION_GIFT)
                .where(TPromotionGift.T_PROMOTION_GIFT.GIFT_PROMOTIONS.in(promotionIds))
                .execute();
    }

}
