/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TProductCategoryPromotion;
import com.vjshop.generated.db.tables.records.TProductCategoryPromotionRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TProductCategoryPromotionDao extends JooqBaseDao<TProductCategoryPromotionRecord, com.vjshop.entity.TProductCategoryPromotion, Long> {

    /**
     * Create a new TProductCategoryPromotionDao without any configuration
     */
    public TProductCategoryPromotionDao() {
        super(TProductCategoryPromotion.T_PRODUCT_CATEGORY_PROMOTION, com.vjshop.entity.TProductCategoryPromotion.class);
    }

    /**
     * Create a new TProductCategoryPromotionDao with an attached configuration
     */
    @Autowired
    public TProductCategoryPromotionDao(Configuration configuration) {
        super(TProductCategoryPromotion.T_PRODUCT_CATEGORY_PROMOTION, com.vjshop.entity.TProductCategoryPromotion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TProductCategoryPromotion object) {
        return compositeKeyRecord(object.getProductCategories(), object.getPromotions());
    }

    /**
     * Fetch records that have <code>product_categories IN (values)</code>
     */
    public List<com.vjshop.entity.TProductCategoryPromotion> fetchByProductCategories(Long... values) {
        return fetch(TProductCategoryPromotion.T_PRODUCT_CATEGORY_PROMOTION.PRODUCT_CATEGORIES, values);
    }

    /**
     * Fetch records that have <code>promotions IN (values)</code>
     */
    public List<com.vjshop.entity.TProductCategoryPromotion> fetchByPromotions(Long... values) {
        return fetch(TProductCategoryPromotion.T_PRODUCT_CATEGORY_PROMOTION.PROMOTIONS, values);
    }
}
