/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TReturns;
import com.vjshop.generated.db.tables.records.TReturnsRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TReturnsDao extends JooqBaseDao<TReturnsRecord, com.vjshop.entity.TReturns, Long> {

    /**
     * Create a new TReturnsDao without any configuration
     */
    public TReturnsDao() {
        super(TReturns.T_RETURNS, com.vjshop.entity.TReturns.class);
    }

    /**
     * Create a new TReturnsDao with an attached configuration
     */
    @Autowired
    public TReturnsDao(Configuration configuration) {
        super(TReturns.T_RETURNS, com.vjshop.entity.TReturns.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TReturns object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchById(Long... values) {
        return fetch(TReturns.T_RETURNS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TReturns fetchOneById(Long value) {
        return fetchOne(TReturns.T_RETURNS.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByCreateDate(Timestamp... values) {
        return fetch(TReturns.T_RETURNS.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByModifyDate(Timestamp... values) {
        return fetch(TReturns.T_RETURNS.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByVersion(Long... values) {
        return fetch(TReturns.T_RETURNS.VERSION, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByAddress(String... values) {
        return fetch(TReturns.T_RETURNS.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>area IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByArea(String... values) {
        return fetch(TReturns.T_RETURNS.AREA, values);
    }

    /**
     * Fetch records that have <code>delivery_corp IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByDeliveryCorp(String... values) {
        return fetch(TReturns.T_RETURNS.DELIVERY_CORP, values);
    }

    /**
     * Fetch records that have <code>freight IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByFreight(BigDecimal... values) {
        return fetch(TReturns.T_RETURNS.FREIGHT, values);
    }

    /**
     * Fetch records that have <code>memo IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByMemo(String... values) {
        return fetch(TReturns.T_RETURNS.MEMO, values);
    }

    /**
     * Fetch records that have <code>operator IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByOperator(String... values) {
        return fetch(TReturns.T_RETURNS.OPERATOR, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByPhone(String... values) {
        return fetch(TReturns.T_RETURNS.PHONE, values);
    }

    /**
     * Fetch records that have <code>shipper IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByShipper(String... values) {
        return fetch(TReturns.T_RETURNS.SHIPPER, values);
    }

    /**
     * Fetch records that have <code>shipping_method IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByShippingMethod(String... values) {
        return fetch(TReturns.T_RETURNS.SHIPPING_METHOD, values);
    }

    /**
     * Fetch records that have <code>sn IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchBySn(String... values) {
        return fetch(TReturns.T_RETURNS.SN, values);
    }

    /**
     * Fetch a unique record that has <code>sn = value</code>
     */
    public com.vjshop.entity.TReturns fetchOneBySn(String value) {
        return fetchOne(TReturns.T_RETURNS.SN, value);
    }

    /**
     * Fetch records that have <code>tracking_no IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByTrackingNo(String... values) {
        return fetch(TReturns.T_RETURNS.TRACKING_NO, values);
    }

    /**
     * Fetch records that have <code>zip_code IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByZipCode(String... values) {
        return fetch(TReturns.T_RETURNS.ZIP_CODE, values);
    }

    /**
     * Fetch records that have <code>orders IN (values)</code>
     */
    public List<com.vjshop.entity.TReturns> fetchByOrders(Long... values) {
        return fetch(TReturns.T_RETURNS.ORDERS, values);
    }
}
