/*
 * This file is generated by jOOQ.
*/
package com.vjshop.dao;


import com.vjshop.generated.db.tables.TShippingItem;
import com.vjshop.generated.db.tables.records.TShippingItemRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TShippingItemDao extends JooqBaseDao<TShippingItemRecord, com.vjshop.entity.TShippingItem, Long> {

    /**
     * Create a new TShippingItemDao without any configuration
     */
    public TShippingItemDao() {
        super(TShippingItem.T_SHIPPING_ITEM, com.vjshop.entity.TShippingItem.class);
    }

    /**
     * Create a new TShippingItemDao with an attached configuration
     */
    @Autowired
    public TShippingItemDao(Configuration configuration) {
        super(TShippingItem.T_SHIPPING_ITEM, com.vjshop.entity.TShippingItem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.vjshop.entity.TShippingItem object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchById(Long... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.vjshop.entity.TShippingItem fetchOneById(Long value) {
        return fetchOne(TShippingItem.T_SHIPPING_ITEM.ID, value);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByCreateDate(Timestamp... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>modify_date IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByModifyDate(Timestamp... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.MODIFY_DATE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByVersion(Long... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.VERSION, values);
    }

    /**
     * Fetch records that have <code>is_delivery IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByIsDelivery(Boolean... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.IS_DELIVERY, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByName(String... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.NAME, values);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByQuantity(Integer... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>sn IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchBySn(String... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.SN, values);
    }

    /**
     * Fetch records that have <code>specifications IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchBySpecifications(String... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.SPECIFICATIONS, values);
    }

    /**
     * Fetch records that have <code>product IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByProduct(Long... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.PRODUCT, values);
    }

    /**
     * Fetch records that have <code>shipping IN (values)</code>
     */
    public List<com.vjshop.entity.TShippingItem> fetchByShipping(Long... values) {
        return fetch(TShippingItem.T_SHIPPING_ITEM.SHIPPING, values);
    }
}
